### ISSUE TITLE
RFC: Let's close all the TSC Meeting agendas/notes (eventually)

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm/discussions#106]
Active discussions and RFC's are difficult to find in the issue list here.

I think we could do something like this.
- Meeting occurs following a previously posted agenda
- After the meeting:
  - post the meeting notes as a reply to the meeting agenda
  - in another comment, draft next month's meeting agenda (esp to list anything that needs follow-up in the next meeting)
  - close the previous month's meeting agenda/notes
- The week before the next meeting:
  - create a new issue for the next meeting
    - copy the draft agenda from the previous meeting comment
    - add/adjust agenda items as necessary
    - label it with `TSC:meeting`
  - post a link to the new issue in the #tsc issue on slack

This way, no more than 2 meetings' agendas will be open at a time. The last meeting's agenda is always open, and for 1 week, the next meeting's agenda will also be open.

If a topic from a meeting warrants additional discussion, then that should probably go in a separate issue that links to the Meeting notes where it was discussed.

If someone needs to look up something from a previous meeting's notes, it is still relatively easy to find via both the label and search.

Thoughts?

**Comment by rush-skills** [comment]
+1, I too was getting lost in the community issues between all the open TSC meetings.

**Comment by arm4b** [comment]
Sure, I'm good with the idea of closing the old TSC Meeting issues if that's an inconvenience to other folks. For me, it's just a forum that's there for informational purposes ordered by the history and not a list of closed/open tasks.

The Meeting preparation process is documented in https://github.com/StackStorm/community/issues/33
+1 good idea to track the follow-ups, deliverables, and expectations from the previous meeting to the next.

I'd still recommend drafting quickly the meeting agenda in the TSC chat (like @rush-skills did https://stackstorm-community.slack.com/archives/C020U70RZRR/p1657026964136659) before posting a final issue (which automatically appears in Slack via Github integration).
Easy step, but it's based on the previous experience that brings better consensus and ideas on the Meeting Agenda before announcing it.

**Comment by amanda11** [comment]
I'm happy with this.

**Comment by arm4b** [comment]
Closing as resolved, per https://github.com/StackStorm/community/issues/107 discussion we'll keep open only the active Issues.
