### ISSUE TITLE
TSC Meeting (06 Sept 2022)

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm/discussions#108]
September 2022 @StackStorm/tsc `1 hour` planned meeting: Tuesday, `06 September 2022, 09:30 AM US Pacific`.

See #33 for more info on how to join.
(TLDR; Zoom link: https://us02web.zoom.us/j/81082101702?pwd=N1V4TWdYRVQ4SXBsaFh1TFYvVDA0UT09)

### TSC meeting host rotation - @armab

https://github.com/StackStorm/st2/pull/5711

### v3.8 release discussions - @nzlosh
  - Pending Tasks? Target Date?
  - Release Manager: @nzlosh
  - Release Assistant: @rush-skills

### `pants` migration status update - @cognifloyd

- https://github.com/StackStorm/st2/pull/5713
    - 6 TSC Approvals
- How do we want to handle reviewing this?
- How do we want to handle training around working with pants?
- How quickly should we move?

### Cost Reduction

- https://github.com/StackStorm/community/issues/36
- https://github.com/StackStorm/community/issues/104
- AWS Cost Reduction project: https://github.com/orgs/StackStorm/projects/27
    - https://github.com/StackStorm/community/issues/76
        - https://github.com/StackStorm/stackstorm.com
    - https://github.com/StackStorm/st2docs/issues/1096
    - https://github.com/StackStorm/st2docs/pull/1129
    - https://github.com/StackStorm/st2apidocs/issues/16

**Comment by arm4b** [comment]
@cognifloyd Could we include [ [RFC] TSC Governance Proposal: Document the TSC Meetings host rotation #5711](https://github.com/StackStorm/st2/pull/5711) to the meeting agenda?

**Comment by cognifloyd** [comment]
Attendees
@amanda11 @armab @bishopbm1 @cognifloyd @rush-skills

## Meeting Notes

### Choose meeting host the next meeting (4 Oct 2022)

@bishopbm1 Bradley Bishop will be the next meeting host

For future meetings we will choose the next host asynchronously so that we can get more TSC members involved.

### TSC RFC/RFRs

We need more reviews on
- https://github.com/StackStorm/st2/pull/5719
- https://github.com/StackStorm/st2/pull/5711

### v3.8 Release Discussion

v3.8 is not dependent on the pants changes to be fully merged because the CI should run in parallel.
@rush-skills will work with @nzlosh to see what is needed to get the next release out.

### `pants` migration status update

6 TSC members reviewed https://github.com/StackStorm/st2/pull/5713

We decided that we will get pants support merged as quickly as possible (merge once each PR gets the standard 2 reviews). We will update the WIP docs PR throughout this process. Then, other TSC members will learn about pants by reviewing and trying things out according to those updated docs. Some TSC members will avoid reviewing any of the pants-related PRs so that they can review the docs with a fresh set of eyes to ensure that they are clear for contributors, new and old.

All of the pants PRs will leave the old CI / dev infrastructure intact so that the pants-based CI runs in parallel with the old methods. The docs have to be merged before we remove the old CI/dev infrastructure, and the first of the PRs to remove that will need more than the standard 2 reviews to make sure we haven't missed something.

Hopefully we can use `pants` as part of the 3.9 release.

### Cost Reduction

We've made amazing progress with reducing costs. Big thanks to Encore for sponsoring the AWS parent account - we're now down to about $40/month in expenses.

### Website Theme

The website has been changed to static pages (part of cost reduction). It is now very difficult to update the website and blog. We need new Hugo theme(s) for stackstorm.com and the blog - matching the current style exactly will probably require far too much effort, so a new theme is probably required. We should send out a call for theme designs, possibly through Twitter and other social media platforms.

### Security Documentation

@bishopbm1 is compiling documentation about security practices. Once ready, the TSC will review it before publishing.

Current security-related documentation:
- https://docs.stackstorm.com/security.html
- https://stackstorm.com/security/
- https://github.com/StackStorm/st2/blob/master/SECURITY.md

@armab pointed out some additional resources:
> One interesting is https://bestpractices.coreinfrastructure.org/en/projects/1833#security that has some checkboxes on the security side, like how the project handles security specifics. There are more to evaluate for the `silver` https://bestpractices.coreinfrastructure.org/en/projects/1833?criteria_level=2#security  and `gold`  level criteria: https://bestpractices.coreinfrastructure.org/en/projects/1833?criteria_level=1#security that needs more research how that applies to st2 codebase and practices. I guess that might be a bit more relevant to what you mentioned.
>
> For the context, [OpenSSF Best Practices](https://bestpractices.coreinfrastructure.org/en) is a LF project that evaluates project quality based on different criteria. We have a `passing` badge there on the stackstor/st2 [README](https://github.com/StackStorm/st2/blob/master/README.md).

### Offline Installation

@bishopbm1 asked about how interested we are in offline installation. This is a recurring issue, so we're open to doc improvements and other changes to facilitate this.
@armab noted existing resources about / requests for offline installation:
- https://stackstorm.com/2017/02/10/installing-stackstorm-offline-systems/
- https://github.com/StackStorm/st2/issues/3841
