### ISSUE TITLE
TSC Meeting (4 Oct 2022) - v3.8.0 Release Preparation

### ISSUE THREAD

**Issue by bishopbm1** [StackStorm/discussions#111]
October 2022 @StackStorm/tsc `1 hour` planned meeting: Tuesday, `4 October 2022, 09:30 AM US Pacific`.

See #33 for more info on how to join.
(TLDR; Zoom link: https://us02web.zoom.us/j/81082101702?pwd=N1V4TWdYRVQ4SXBsaFh1TFYvVDA0UT09)

### TSC meeting host rotation - @armab

https://github.com/StackStorm/st2/pull/5711

### v3.8 release discussions - @nzlosh
  - Pending Tasks? Target Date?
  - Release Manager: @nzlosh
  - Release Assistant: @rush-skills

### `pants` migration status update - @cognifloyd

- Any updates on status?

### Cost Reduction

- https://github.com/StackStorm/community/issues/36
- https://github.com/StackStorm/community/issues/104
- AWS Cost Reduction project: https://github.com/orgs/StackStorm/projects/27
    - https://github.com/StackStorm/community/issues/76
        - https://github.com/StackStorm/stackstorm.com
    - https://github.com/StackStorm/st2docs/issues/1096
    - https://github.com/StackStorm/st2docs/pull/1129
    - https://github.com/StackStorm/st2apidocs/issues/16

### st2-self-check - @winem 
https://github.com/StackStorm/st2/pull/5609

**Comment by mickmcgrath13** [comment]
Should this be "TSC Meeting (4 Oct 2022)" not "TSC Meeting (14 Oct 2022)"?

**Comment by mickmcgrath13** [comment]
We also have a quick update on some st2web PRs:
- https://github.com/StackStorm/st2web/pull/963
- https://github.com/StackStorm/st2web/pull/964
- https://github.com/StackStorm/st2web/pull/965

**Comment by bishopbm1** [comment]
Meeting Minutes:
Bradley Shared security page with team as a start of security standards letting people comment on it.

We discussed Versioning and changelog around st2web/st2chatops.

@cognifloyd is moving on to linting sections of pants build out.

Security concerns were discussed and members were assigned to continue to track down fixes.

Request for review on above noted PRs.

Attendees:
@bishopbm1 
@rush-skills 
@armab 
@amanda11 
@winem 
@nzlosh 
@rush-skills 
@cognifloyd
