### ISSUE TITLE
TSC Meeting (14 Feb 2023) - Python3 and Pants

### ISSUE THREAD

**Issue by arm4b** [StackStorm/discussions#117]
February 2023 @StackStorm/tsc `1 hour` meeting plan:
- `Tuesday, 14 February 2022, 09:30 AM US Pacific`.
- See https://github.com/StackStorm/community/issues/33 for the schedule.
- TLDR; Zoom link: https://us02web.zoom.us/j/81082101702?pwd=N1V4TWdYRVQ4SXBsaFh1TFYvVDA0UT09

### Updates & Notes
  - Security and https://github.com/orgs/StackStorm/projects/25
  - ST2 Domains & LF
  - Vagrant build https://github.com/StackStorm/packer-st2/ by @mamercad
  - st2docs theme changes https://docs.stackstorm.com/latest/ by @cognifloyd 

### Pants progress
Progress and overview of the Pants builds effort https://github.com/StackStorm/st2/labels/pantsbuild

### Python 3: next steps
What's the future for StackStorm builds, Python3 version matrix, OS support.

**Comment by cognifloyd** [comment]
I'd also like to talk about GitHub's new merge queue feature.

**Comment by cognifloyd** [comment]
Attendees:
@amanda11, @armab, @cognifloyd, @dalesmith, @guzzijones, @mamercad, @nzlosh, @rush-skills, @winem

Quick Summary: 
- let's be more secure. We're making progress here.
- packer-st2 is working now! Thanks @mamercad
- docs theme updated and PRs are now built on ReadTheDocs. Changes need to be cherry-picked to 3.8 branch.
- Lot of things are waiting on the pants migration which is progressing nicely.
- Someone needs to test how the new github merge queue handles conflicts like we have with CHANGELOG.rst in a separate repo before we try to add support for it in the StackStorm/st2 repo.
