### ISSUE TITLE
Proposal: Replace gulp with a modern build system for st2web

### ISSUE THREAD

**Issue by blag** [StackStorm/discussions#23]
# Motivation #

The Gulp build system is no longer supported, but the st2web repository has not been updated to use something else. This increases the signal-to-noise ratio of dependency alerts we receive for that repository. Luckily, a lot of the outdated dependencies are only development dependencies that will never see production, but automated scanners will still report those to us, and might cause us to miss an outdated non-development dependency, since it "normalizes deviance".

# Solution #

We should replace the current build system, Gulp, with something that is maintained, like Webpack.

## Downsides ##

We don't have a lot of front end developers, so this may be a lot of effort for the developers that we do have. However, switching to a more modern, updated build system might lower the barrier to contribute, thereby making it easier for more frontend developers to engage with the project and contribute additional fixes and features.

# Alternatives #

We can just live with the out-of-date development dependency notifications, _as long as_ we guarantee that they aren't used in production. This seems fairly easy to guarantee, but not necessarily easy to live with.

---------------------------------------

I am not a frontend developer, so it would be helpful to have at least one or two frontend developers weigh in on this (paging @guzzijones and @bgaeddert).

**Comment by guzzijones** [comment]
Afaik gulp is still supported. What package specifically are we talking to?
Let me do some digging again today and get you some specifics here to help.

I dont have a ton of gulp experience. I usually just use create react app for my projects.

Webpack does a lot of things gulp does, Yes.

**Comment by guzzijones** [comment]
```
[ubuntu@ip-128-126-44-42]~/projects/st2web$ npm ls gulp-util
st2web@2.4.3 /home/ubuntu/projects/st2web
└─┬ @stackstorm/st2-build@2.4.3 -> /home/ubuntu/projects/st2web/tasks
  ├── gulp-util@3.0.8
  └─┬ gulp-webserver@0.9.1
    └── gulp-util@2.2.20
```
Not  used in the codebase.  
https://github.com/StackStorm/st2web/pull/756

**Comment by guzzijones** [comment]
spoke on the phone about his with @punkrokk .  gulp is not deprecated.  We are sticking with gulp.  The above PR removes an unused dependency on deprecated gulp-util

**Comment by blag** [comment]
Thanks for the feedback @guzzijones! Closing.
