### ISSUE TITLE
Game plan: EL6 Deprecation (v3.3.0)

### ISSUE THREAD

**Issue by arm4b** [StackStorm/discussions#39]
Per Roadmap (https://docs.stackstorm.com/roadmap.html#id1), `CentOS 6` / `RHEL 6` will be fully deprecated and removed in the `v3.3.0` release.

This includes a lot of very easy and small tasks related to OS cleanup across the StackStorm repositories and we encourage Community to help there. There are perfect tasks for the new Contributors and will introduce you to the different platform places.

Here are the pointers in different StackStorm org repositories to remove the el6 support:
## Plan: https://github.com/orgs/StackStorm/projects/17
- [x] `st2`
  - [x] stop the EL6 build in CircleCI https://github.com/StackStorm/st2/pull/4984 (@amanda11)
  - [x] identify/close any EL6 related issues
  - [x] remove any EL 6-specific code paths
- [x] `st2-packages`
  - [x] update scripted installer to remove EL6 support https://github.com/StackStorm/st2-packages/pull/654 (@eorochena)
  - [x] remove EL6 `rpm` scriptlets and init scripts https://github.com/StackStorm/st2-packages/pull/658 (@armab)
  - [x] remove st2python package - only actual for EL6 https://github.com/StackStorm/st2-packages/pull/658 (@armab)
  - [x] stop the EL6 build in CircleCI https://github.com/StackStorm/st2-packages/pull/654 (@eorochena)
- [x] `st2chatops` - stop CircleCI builds and remove EL6 `rpm` scriptlets https://github.com/StackStorm/st2chatops/pull/153 (@amanda11)
- [x] `st2web` - stop CircleCI builds and remove EL6 `rpm` scriptlets https://github.com/StackStorm/st2web/pull/768 (@amanda11)
- [x] [`st2-enterprise-auth-backend-ldap`](https://github.com/stackstorm/st2-enterprise-auth-backend-ldap) - stop CircleCI builds producing EL6 `rpm` https://github.com/StackStorm/st2-enterprise-auth-backend-ldap (@amanda11)
- [x] [`st2-enterprise-rbac-backend`](https://github.com/StackStorm/st2-enterprise-rbac-backend) - stop CircleCI builds producing EL6 `rpm` https://github.com/StackStorm/st2-enterprise-rbac-backend/pull/36 (@amanda11)
- [x] [`st2-enterprise-sso-backend`](https://github.com/StackStorm/st2-enterprise-sso-backend) - stop CircleCI builds producing EL6 `rpm` https://github.com/StackStorm/st2-enterprise-sso-backend/pull/12 (@amanda11)
- [x] [`st2packaging-dockerfiles`](https://github.com/stackstorm/st2packaging-dockerfiles) https://github.com/StackStorm/st2packaging-dockerfiles/pull/89 (@sheshagiri and @amanda11) - remove EL6 Dockerfiles
- [x] `ansible-st2` https://github.com/StackStorm/ansible-st2/issues/267 (@amanda11)
- [x] `puppet-st2` https://github.com/StackStorm/puppet-st2/pull/305 (@nmaludy)
- [x] `chef-stackstorm` - repo to be deprecated and archived (@armab)
- [x] [`st2ci`](https://github.com/stackstorm/st2ci) https://github.com/StackStorm/st2ci/pull/188 update to stop e2e testing EL6 packages
- [x] [`st2cd`](https://github.com/stackstorm/st2cd) https://github.com/StackStorm/st2cd/pull/439 update to stop promoting EL6 packages
  - [x] sync-up [Release Checklist](https://github.com/StackStorm/discussions/wiki/Release-Process) 
- [x] `st2docs` https://github.com/StackStorm/st2docs/pull/994 update to remove EL6 installation/support
  - [x] roadmap update
- [ ] Announce full EL6 deprecation in the `v3.3.0` blog post

If you have any questions, - feel free to ask here or in `#development` channel of StackStorm Community Slack: https://stackstorm.com/#community

**Comment by eorochena** [comment]
@armab happy to take a stab at st2-packages, I will check with the community if I get stuck somewhere.

**Comment by arm4b** [comment]
Closing as all the items of the EL6 deprecation roadmap are finished.

Thanks @amanda11, @eorochena, @Sheshagiri, @nmaludy for the collective work and everyone who helped with review!
