### ISSUE TITLE
TSC Meeting (1 Sep 2020): Community, v3.3.0 Release, ChatOps, OSS Economy

### ISSUE THREAD

**Issue by arm4b** [StackStorm/discussions#47]
Another @StackStorm/tsc 1 hour meeting will take place on Tuesday, `1st Sep 2020, 09:30 AM US Pacific`.
See #33 for more info about how to join.

## Meeting Agenda
- Community:
  - StackStorm Japan Community (@userlocalhost)
  - @amanda11 new TSC member (https://github.com/StackStorm/st2/pull/5018)
  - New @StackStorm/contributors GitHub group (https://github.com/StackStorm/st2/pull/5019)
  - @sheshagiri new Contributor (https://github.com/StackStorm/st2/pull/5022)
  - @guzzijones new Contributor (https://github.com/StackStorm/st2/pull/5025)
  - @lindsayhill leaving TSC (https://github.com/StackStorm/st2/pull/5028)
- State of the [v3.3.0 Release](https://github.com/orgs/StackStorm/projects/11) (Release Manager @punkrokk)
  - Security fixes: https://github.com/orgs/StackStorm/projects/10
  - ~EL6 Deprecation: https://github.com/StackStorm/discussions/issues/39~ (Done by @amanda11)
  - Mistral Deprecation: https://github.com/orgs/StackStorm/projects/16 (@amanda11)
  - EWC -> OSS Workflow Designer integration (@mickmcgrath13)
  - Orquesta Convert (@nmaludy)
- ChatOps User Survey #19 (@blag)
- PackageCloud, Expenses and Extreme Networks (@m4dcoder)
  - See [StackStorm Expenses](https://github.com/StackStorm/discussions/issues/36) for more context
- Open Source Economy
  - Slack Privacy Vote #45
  - StackStorm Partners
- ST2 Stickers Update, StackStorm-Exchange (@nmaludy)

We have limited time (1 hour) to cover main topics, but please add in comments any other questions or problems you'd like to raise for this/next meeting or even to discuss async.

**Comment by userlocalhost** [comment]
@armab Thank you very much for inviting me to TSC meeting. Here is the outline I will tell you at there.
```
* self-introduction
  - Who I am.
    - Hiroyasu OHYAMA (plz call me "Hiro")
  - A trigger to be involved in ST2 user community.

* StackStorm User Group Japan's activities
  - with (Brocade and) Extreme Networks.
  - without Extreme Networks.
    (c.f. https://stackstorm.jp/ (NOTE: this page is only Japanese))

* Reflection
  - inconstant activity

* Next Action Plan
  - Collaboration with other related events
    (c.f. https://connpass.com/calendar/ (NOTE: this page is also only Japanese))
  - Online Meetup
```

I'll finish it off quickly as much as possible, but it might take 3-4 minutes.

**Comment by arm4b** [comment]
Notes Based on the TSC Meeting: 

## Attendees
Total `~20` attendees present
- Host: @armab 
- @StackStorm/maintainers (8/10): @dzimine @m4dcoder @blag @armab @punkrokk @amanda11 @nmaludy @mickmcgrath13 
- @StackStorm/contributors: @winem, @carlos, @guzzijones, @jjm, @userlocalhost

Thanks everyone for joining!

### Community
- @userlocalhost (Hiroyasu OHYAMA aka Hiro) and his friends were doing great work building StackStorm Community in Japan for many years (!). See https://stackstorm.com/case-study-dmm/ This is huge hidden work, unnoticed by the main English-speaking st2 community.  They have `#community-japan` channel with around `~100` members and organized a lot of StackStorm meetings. StackStorm TSC would be happy to provide any kind of cover to help with @userlocalhost effort to continue building the StackStorm-Japan Communtiy which was a bit of more challenge recently during this hard time.
- @userlocalhost recorded the meeting to share with the StackStorm Japan and will continue leading and growing StackStorm Japan Community.

### v3.3.0 Release
  - @punkrokk provided an update about the current state of the `v3.3.0` release. We're getting closer.
  - @punkrokk did great work pushing the [v3.3.0 Release Project](https://github.com/orgs/StackStorm/projects/11) forward working with team members on items completion and follow-ups.
  - Due to some time constraints from @punkrokk side, @nmaludy will take over the Release Manager role for upcoming `v3.3.0`, @blag will be assisting as well as entire @StackStorm/maintainers group.
  - Because [Add Python 2.7 deprecation warning](https://github.com/StackStorm/st2/issues/4938) is part of the `v3.3.0` release items: @StackStorm/maintainers team needs a decision and execution on that (part of the bigger [Python 2 Deprecation](https://github.com/StackStorm/discussions/issues/40) plan).
  - It took 4 months for now to prepare the v3.3.0 so far
  - v3.3.0 major roadmap items like EL6 and Mistral removal work is complete and was `90%` done by @amanda11
  - Some st2web and st2chatops required security updates were on-boarded, some are still missing or in progress
  - `st2flow` Workflow Designer integration might be late and be shifted to the next st2 release if team is ready to cut the v3.3.0. If st2flow integration will be ready, - it will be a good bonus for the v3.3.0. **Help wanted!** https://github.com/StackStorm/st2web/pull/759 (by @mickmcgrath13)

### ChatOps User Survey
- @blag was leading the ChatOps and presented very detailed results report based on ChatOps User Survey
- There were items we already know (like RBAC functionality everyone wants), but there was also some surprising data 
- Community was very supportive in providing their feedback and willing to give a hand of help to improve the chatops.
- It's great to have so many ChatOps advocates, - we'll need to engage them more into upcoming st2 chatops story.
- @blag will write a Discussion with the report/stats so TSC and Community could analyze it, make conclusions based on data and talk about the plan and next steps for StackStorm ChatOps
- @dzimine proposed to write a blog post to further engage the chatops community and share the results from the insightful Survey Results.

### PackageCloud, Expenses and Extreme Networks (@m4dcoder)
We didn't have time to cover that due to other items discussed
- Extreme will stop covering the [StackStorm Expenses](https://github.com/StackStorm/discussions/issues/36) soon in December. This is part of the StackStorm/OSS Economy talk, we'll cover it as priority during the next TSC meeting.

### Open Source Economy 
- @dzimine raised a question about the OSS Economy and the fact that project support is not possible without $ cover.
- StackStorm Partners: More than a half of TSC members provide commercial support/services on top of ST2 OSS. Because team couldn't cover this topic, @armab will compose a Github Discussion about the Economy, different groups, their Interests, Community and StackStorm Partners page as a way for some TSC members to benefit from their maintenance and support of StackStorm project. This would also highlight the StackStorm expenses topic.
