### ISSUE TITLE
2020 ChatOps User Survey Results

### ISSUE THREAD

**Issue by blag** [StackStorm/discussions#48]
## Question 2 ##

![Screenshot_2020-09-01 SurveyMonkey Analyze - 2020 ChatOps User Survey(1)](https://user-images.githubusercontent.com/597113/91906558-3eec2b00-ec5d-11ea-9ef2-7c61a9c2fe96.png)

## Question 3 ##

![Screenshot_2020-09-01 SurveyMonkey Analyze - 2020 ChatOps User Survey(2)](https://user-images.githubusercontent.com/597113/91906580-47446600-ec5d-11ea-99a3-685d6cd37e5f.png)

## Question 4 ##

![Screenshot_2020-09-01 SurveyMonkey Analyze - 2020 ChatOps User Survey(3)](https://user-images.githubusercontent.com/597113/91906678-7529aa80-ec5d-11ea-9925-74a3db6b1d5f.png)

## Question 5 ##

![Screenshot_2020-09-01 SurveyMonkey Analyze - 2020 ChatOps User Survey(4)](https://user-images.githubusercontent.com/597113/91906687-7a86f500-ec5d-11ea-84da-4392dcbf0e07.png)

## Question 6 ##

![Screenshot_2020-09-01 SurveyMonkey Analyze - 2020 ChatOps User Survey(5)](https://user-images.githubusercontent.com/597113/91906696-7d81e580-ec5d-11ea-9065-3ac061ebf3ee.png)

Other responses:

* > Busy with other priorities
* > We use a Matrix based chat platform which I don't think StackStorm supports. We also have limited resources to devote just to implement chatops
* > Not convinced ChatOps in general is a good operational model
* > We are using Microsoft Teams. And we have a barrier of house rule about security. When we use chatbot, we have to break the barrier.
* > Terrible chat tools.

#### What chat application/s do you use that are not supported? ####

Microsoft Teams

## Question 8 ##

![Screenshot_2020-09-01 SurveyMonkey Analyze - 2020 ChatOps User Survey(6)](https://user-images.githubusercontent.com/597113/91906710-81ae0300-ec5d-11ea-90fb-229732242886.png)

## Question 9 ##

![Screenshot_2020-09-01 SurveyMonkey Analyze - 2020 ChatOps User Survey(7)](https://user-images.githubusercontent.com/597113/91906721-85418a00-ec5d-11ea-9c96-2a2dad357ca5.png)

## Question 10 ##

![Screenshot_2020-09-01 SurveyMonkey Analyze - 2020 ChatOps User Survey(8)](https://user-images.githubusercontent.com/597113/91906726-87a3e400-ec5d-11ea-8760-6a66413aa925.png)

Other responses:

* > Operation
* > Change control ; Information Access for field crews
* > Helpdesk
* > Trigger custom application workflows on demand that can reduce toil
* > Company-wide incident management, and intra-team assistance.

## Question 11 ##

![Screenshot_2020-09-01 SurveyMonkey Analyze - 2020 ChatOps User Survey(9)](https://user-images.githubusercontent.com/597113/91906732-8a063e00-ec5d-11ea-903c-e298dc343b87.png)

Other responses:

* > Comunication by StackStorm
* > Disabled pending an access control solution.
* > Mainly reporting triggered actions into Slack, quasi-logging style.
* > Notifications
* > Inquiries and responding via slack
* > Working on integrating our own BotKit framework so we can utilize Slack forms with action-aliases.

## Question 12 ##

![Screenshot_2020-09-01 SurveyMonkey Analyze - 2020 ChatOps User Survey(10)](https://user-images.githubusercontent.com/597113/91906750-8d012e80-ec5d-11ea-8710-aac7466fadaf.png)

Other responses:

* > Provide simplistic access to items in 3rd party APIs - eg. who is oncall in PD
* > OpsGenie notifications / stage database refresh and app restart
* > Start video meetings, create documents from a template, page teams by name, manage alias notifications (on/off)
* > Allow tier 1 support to run an Ops process (an ansible playbook) that updates config at a customer location.

## Question 13 ##

![Screenshot_2020-09-01 SurveyMonkey Analyze - 2020 ChatOps User Survey(11)](https://user-images.githubusercontent.com/597113/91906756-8ffc1f00-ec5d-11ea-9453-4a8b78a16341.png)

## Question 14 ##

![Screenshot_2020-09-01 SurveyMonkey Analyze - 2020 ChatOps User Survey(12)](https://user-images.githubusercontent.com/597113/91906760-94c0d300-ec5d-11ea-9bdf-3d8fe44a625f.png)

## Question 15 ##

Summary: Slack and Microsoft Teams

![Screenshot_2020-09-01 SurveyMonkey Analyze - 2020 ChatOps User Survey(13)](https://user-images.githubusercontent.com/597113/91906767-98ecf080-ec5d-11ea-98c0-a0aa28f6264e.png)

## Question 16 ##

![Screenshot_2020-09-01 SurveyMonkey Analyze - 2020 ChatOps User Survey(14)](https://user-images.githubusercontent.com/597113/91906776-9d190e00-ec5d-11ea-8d80-9f5733ab97cf.png)

Other responses:

* > More straightforward/easier MSTeams
* > If not RBAC, at least some kind of manual user whitelist
* > Interactive aliases
* > Utilize / (slash) commands in slack rather than though hubot
* > Better chatops support for Webex Teams, EWC released to the wild and a key to support the installation
* > Better control over output (paging, maximum message size, text formatting respected for paged output.)
* > MS Teams
* > Permitting and restricting different aliases per Slack channel (may get this with better RBAC integration)

## Question 17 ##

![Screenshot_2020-09-01 SurveyMonkey Analyze - 2020 ChatOps User Survey(15)](https://user-images.githubusercontent.com/597113/91906782-a0ac9500-ec5d-11ea-89a3-d4f667e5e5a2.png)

#### What does StackStorm get right with its existing ChatOps implementation? ####

1. Slack integration and configuration
2. User-defined ChatOps is useful
3. It's easy to write and run action aliases
4. ChatOps and workflow notifications are nice
5. ChatOps just works
6. Modularity
7. Notifications and customization of action aliases
8. Chat provider agnostic
9. The ability to interact with ChatOps in the middle of a workflow and respond via ChatOps
10. Action aliases make it easy to be DRY

#### What does StackStorm get wrong with its ChatOps implementation? ####

1. No RBAC for ChatOps
2. Inquiries are difficult, and interactivity is limited
3. Microsoft Teams configuration is difficult and integration is not good
4. Third party plugins are sometimes unmaintained or unresponsive, which makes it difficult to get pull requests merged to fix bugs in hubot-stackstorm.
5. ChatOps should be written in Python
6. Action alias formatting isn't simple and robust
7. Lack of two-way communication with the user (trying to remember formatting is difficult for some users)

#### Is there anything we should do to make it easier to use ChatOps with StackStorm? ####

1. Support RBAC in ChatOps, or a simple "user whitelist" access control at a bare minimum
2. Improve quality and quantity of examples and documentation; possibly a beginner's guide
3. Rewrite ChatOps in Python
4. Better Microsoft Teams integration
5. Better support for interactivity, including inquiries
6. Better Webex Teams support
7. Auto-parse actions so any action can be used without special config
8. Allow for inquiries to be sent to users to gather the information [note: I believe this refers to when ChatOps users don't know a full command, so ChatOps should query for the missing commands]

#### Is there anything we absolutely should NOT do regarding ChatOps in StackStorm? ####

1. > Inquiries are complex
2. Don't drop support for ChatOps! This is a main driver of ST2 within an organization
3. > Do not use BotFramework for anything else. Microsoft Teams is bad enough.

#### Would you be willing to help us refactor, redesign, develop, or test new ChatOps features? ####

Summary: Mostly yes.

#### Would you be willing to have a deeper discussion with us about your ChatOps use case/s? ####

Summary: Half yes, half no.

**Comment by arm4b** [comment]
Based on users feedback we know that people really want the StackStorm ChatOps RBAC.

There is more new data that was interesting to find:
- ChatOps is known to be used in relatively small groups. However data reported that ChatOps is starting to be adopted in 1K or bigger orgs. I mean this is happening. Previously almost everyone from the bigger corps I've talked with told "It's a toy, it doesn't work" about it. With improvements like better Security, RBAC, channel restrictions and more we could make the adoption easier for the bigger players to use StackStorm ChatOps. This could be a new driving factor getting the corp support.
- There is still a huge number of people/orgs "Who never tried ChatOps". That's promising as new potential group to explore.
- NLP idea didn't find good support. I guess It's hard to reliase NLP chatops benefits in infra/operations context where clear command instructions are essential. 
- Microsoft Teams is more important than we think. There were a lot of pain points on this side with the  st2chatops due to technical reasons. Wondering how that could be improved.
- Surprisingly, ChatOps sometimes could be the main driver for using ST2 as a platform. Digging deeper into Analytics, - `chatops` was the major traffic source for docs.stackstorm.com for many years. It's a shame we couldn't use that properly during some past years.
- I also noticed that really good number of people are happy to help us moving the ChatOps story forward: refactor, redesign, develop, test. This is very inspiring and I hope we could engage chatops advocates from StackStorm Community more.


@StackStorm/maintainers @StackStorm/contributors  What are other's observations based on this this Survey? Please share.
