### ISSUE TITLE
TSC Meeting (3 Nov 2020): TSC Chair Election, v3.4.0 Roadmap Planning

### ISSUE THREAD

**Issue by arm4b** [StackStorm/discussions#55]
November monthly @StackStorm/tsc `1 hour` meeting will take place on Tuesday, `3rd Nov 2020, 09:30 AM US Pacific`.
See #33 for more info about how to join.

## Meeting Agenda
- StackStorm [`v3.3.0`](https://stackstorm.com/2020/10/22/stackstorm-v3-3-0-released/) released! #52 (@nmaludy)
- TSC Chair election follow-up https://github.com/StackStorm/discussions/issues/50#issuecomment-704812881  (@dzimine)
  - Discussion about the terms, conditions, mechanism of electing the TSC Chair
  - [Governance.md](https://github.com/StackStorm/st2/blob/master/GOVERNANCE.md#maintainer-roles) will need a change
- StackStorm v3.4.0 Roadmap discussion
   - 3 months release cadence
   - Target: release next st2 version around end of January 2021
   - Next [Release manager](https://github.com/StackStorm/discussions/wiki/Release-Management-Rotation)? 
   - What we want/plan for the next release?
- Follow-up: Python 2 Deprecation plan #53 #40 (@amanda and team)
  - Ubuntu 16 python 3.6 https://github.com/StackStorm/st2docs/pull/1033
  - CentOS 7 python 3.6 #54
  - Ubuntu 20.04 LTS python 3.8 https://github.com/StackStorm/st2docs/pull/1033
- Follow-up: ChatOps #8 (@blag and team)
- Follow-up: [StackStorm infra Expenses](https://github.com/StackStorm/discussions/issues/36), Packagecloud, AWS Migration (@m4dcoder, @armab)
 -  `Donate` button on st2 Web UI https://github.com/StackStorm/st2web/pull/812

cc @StackStorm/maintainers @StackStorm/contributors.

**Comment by dzimine** [comment]
On TSC Chair election - the [proposal drafted](https://github.com/StackStorm/st2/pull/5071), I might have to miss tomorrow's TSC in which case let's pick the discussion in the PR; please use the TSC meeting time to pencil when we want to do the first vote - once process flashed out and agreed, and candidates [self]nominated -  maybe by Dec TSC meeting?

**Comment by arm4b** [comment]
Notes Based on the TSC Meeting:

## Attendees
Total `~15` attendees present.
- Host: @armab 
- @StackStorm/maintainers (7/10): @m4dcoder @blag @armab @punkrokk @amanda11 @nmaludy @mickmcgrath13 
- @StackStorm/contributors: @winem, @nzlosh

Thanks everyone for joining!

## Meeting Minutes

### UK Automtion Meetup Announcement (Thursday, November 12)
  - Organizer: @DavidJohnGee, the StackStorm fellow, ex Brocade, Extreme Networks, currently Juniper Networks
  - Anyone can join: https://www.meetup.com/infra-orchestration-automation-uk/events/273795132/
  - Call for proposals still welcome! (ping `@ipengineer` in Slack)
  - StackStorm will additionally announce/share it to Community via Twitter and LinkedIn
    - https://twitter.com/stack_storm/
    - https://linkedin.com/company/stackstorm/
  - StackStorm would ❤️ to see and support more Community meetups!

### StackStorm v3.3.0 released!
  - The release Automation and everything mostly went fine
  - Great work by the Release Manager - @nmaludy 
  - @nmaludy will write a follow-up `v3.3.0 Retrospective` as a Github Discussion

### TSC Chair Election
  - @dzimine  proposed a mechanism and opened a PR draft https://github.com/StackStorm/st2/pull/5071
  - Question: Private vs Public vote
    - Public would be easier to execute per @nmaludy note
      - otherwise another Voting Coordinator or Voting Automation required
      - DECIDED: @StackStorm/tsc members to write their preference https://github.com/StackStorm/st2/pull/5071#issuecomment-721350092
  - Problem: _TSC Leaders_ vs _TSC Chair_ roles and Governance inconsistency
    - TSC Chair == Leadership role.
    - Initially role with _many_ Leaders was created to fit the TSC Chair responsibilities, distributed between the several persons.
      - adding new role which was assumed to be covered by the Leaders needs a Governance refactoring.
      - concern by @armab: for Governance consistency: define one TSC Chair or keep many TSC Leaders as before.
      - With the new role: 5 tiers in the Governance. Too much of structure!
    - Discussions/work TBD as there are more questions with the 2 overlapping roles.
    - DECIDED: @StackStorm/tsc members should describe their opinions in the [TSC Chair definition and election procedure #5071 ](https://github.com/StackStorm/st2/pull/5071) PR Draft in async way.
### StackStorm `v3.4.0` Roadmap
  - Target: end of the `January 2021`
  - Next release manager?
    - @blag + someone from the new @StackStorm/maintainers?
  - EWC/Enterprise integration
    - Workflow Designer (owner: @m4dcoder)
    - RBAC - packages ready, needs documentation update, testing, release automation, evaluate install flow, productionize (OWNER TBD from @StackStorm/maintainers)
      - needs Ansible, Puppet, Docker, K8s integration follow-up (partially @armab)
    - `LDAP` - packages ready, needs documentation, testing, release automation, , evaluate install flow, productionize (OWNER TBD from @StackStorm/maintainers)
      - needs Ansible, Puppet, Docker, K8s integration follow-up (partially @armab)
    - SSO - half-finished, no documentation, untested. Hold until the next `v3.5.0`? release, unless there is an owner for `v3.4.0`
    - Full EWC/Enterprise Documentation removal (Owner TBD from @StackStorm/maintainers)
  - Python 2 Deprecation meeting follow-up #53 
    - Switch py2 -> py3 for st2 packages under the EL7 platform #54  (@amanda11) 
    - Communicate the py2 deprecation plan to StackStorm Community (@amanda11)
    - Switch py2 -> py3 for st2 packages under the U16 platform (@armab)
    - Add python 3.8 support + in st2 v
    - _Python 2 Deprecation_ Blog announcement to Communicate the plan to the users (@amanda11)
      - intent: help community to be aware about the migration steps and act accordingly.

### ChatOps Follow-Up
  - @blag will organize the meeting (example: #53) to discuss the ChatOps Roadmap/Plans/Migration #8 #48 
  - Intent:
     - get more feedback, engineering folks involved wanting to help and test
     - decide on plan, migration strategy, implementation
     - distribute the work, execute

### Uncovered due to TSC Meeting out of time
- Follow-up: StackStorm infra Expenses, Packagecloud, AWS Migration
- Donate button on st2web (Web UI)
