### ISSUE TITLE
Incentivize and recognize vendor (corporate) contributions

### ISSUE THREAD

**Issue by dzimine** [StackStorm/discussions#59]
> DRAFT

With our goal to grow ST2 community, how can we incentivize the right kind of companies to contribute more, in different forms? 

Given StackStorm specifics, the right community for us is a synergetic balance of **solution providers** - professional service companies like Encore, Bitovi, or Ammeon  who us ST2 to build custom solutions, and some **vendors* (_better term needed_)* - companies who build and sell a product [partially] powered by StackStorm (Extreme with EWC, HP with Plexxi, recently Orchestral.ai). Each company should be incentivized to contribute and rewarded for their contributions; although the rewards might be different for different kind: e.g., professional services may want to generate leads and project credibility, while vendors have no intention to provide services. 

### Problem
StackStorm is currently setup to focus on recognizing individual contributions, not collectively for a company or organization. It works well for technical steering committee where individuals vote for decisions on merits, but breaks for example at the partner page where we recognize and promote companies. Currently, we promote a "founding set of the companies" per one of the early TSC decisions (_citation needed_), and don't have an agreed & documented process for acquiring a "promoted partner" status. A loose way (not documented, lightly discussed) for a company to appear on the partners page so far requires the company to have an individual contributor reach maintainer status. There are key problems with approach, the key are:

1. Maintainer status requires many months for an individual to reach.
2. If the maintainer changes job and there are no other contributors at the company that is a maintainer, the company gets delisted from the partners page.
3. This incentivizes competitor to hire away the maintainer after the investment has already been made.
4. The company may hire many temporary contractors to contribute to StackStorm. The collective contribution is  significant yet the company is not recognized.

We have a particular situation with Orchestral.ai, which 1) is a vendor - will be confusing to mix with promoted partners 2) committed substantial changes but does not have a TSC representative and so far rejected to be placed on partner the on this ground, but also, because they do not provide services. It's prudent to find a way to recognize a company who put trust in StackStorm and incentivize further contributions.  

### Solution - long term
* Separate TCS participation, based on individual meritocracy, from promoting partners - with refined and documented basis for promotion - specifics to be discussed. 
* Map individual contributions to affiliated companies
  * @m4dcoder has an excellent idea how exactly, [JFDI](https://www.amazon.com/JFDI-Just-Fucking-Inspirational-Mr-Motivation/dp/107834258X). 
* Introduce methods to gather metrics on commits by individual and aggregate by company for proper recognition.
* TBD -(DZ: I'll add more) 

### Solution - short term
* Separate System Integrators and Vendors (better name needed) on the Partners page. 
* Introduce a section for Vendors. 
* Include the three vendors there, primarily recognizing the fact of them powering their solutions with StackStorm: 
     1. Extreme (also, in recognition of ongoing support and reflecting @m4dcoder affiliation; to be removed if/when Extreme walks away)
     2. Orchestral.ai (also, in recognition to the accumulated contributions over).
     3. HP / Plexxi (as they do powered by StackStorm, and also as a way to incentivize future contribution / participation).

**Comment by blag** [comment]
Here is the Linux Foundation Insights page:
https://insights.lfx.linuxfoundation.org/projects/stackstorm/dashboard

**Comment by arm4b** [comment]
Was implemented via https://github.com/StackStorm/community/issues/72 with the https://stackstorm.com/partners/ as result.
Closing.
