### ISSUE TITLE
TSC Meeting (12 Jan 2021), v3.4.0

### ISSUE THREAD

**Issue by amanda11** [StackStorm/discussions#60]
January @StackStorm/tsc `1 hour` meeting will take place on Tuesday, `12th January 2021, 09:30 AM US Pacific`.
See #33 for more info about how to join.

## Meeting Agenda (TBC)
- StackStorm [`v3.4.0`](https://github.com/orgs/StackStorm/projects/19) Ongoing work:
  - Release Manager @blag, Release Assistant: @amanda11
  - Target Date: end of January 2021
  - [Python2 Deprecation](https://stackstorm.com/2020/11/15/python-2-deprecation-plan-say-goodbye-to-python-2/) 
    - EL7 with py3 https://github.com/StackStorm/discussions/issues/54
    - U16 with py3
  - RBAC/LDAP Integration https://github.com/orgs/StackStorm/projects/14
  - Workflow Designer https://github.com/StackStorm/st2web/pull/759
  - Project Tasks: https://github.com/orgs/StackStorm/projects/19
- Organization/Partnership proposal (@m4decoder/@dzimine)
  - Incentivize and recognize vendor (corporate) contributions, https://github.com/StackStorm/discussions/issues/59
- Follow-up: ChatOps Roadmap https://github.com/StackStorm/discussions/issues/56 (@blag)
- Follow-up: [StackStorm infra Expenses](https://github.com/StackStorm/discussions/issues/36), Packagecloud and AWS Migration Plan (@m4dcoder)
-  `Donate` button on st2 Web UI https://github.com/StackStorm/st2web/pull/812
- Schedule meeting to investigate TravisCI alternatives (GHA, Conducto, or something else)
- TSC Chairperson follow-up https://github.com/StackStorm/st2/pull/5071 (if @dzimine present)
  - TSC Chair definition, responsibilities, [Governance.md]

**Comment by blag** [comment]
# Notes #

## ST2 v3.4.0 Release ##

* Pushed back one week
  - Code freeze (on `master`) and release testing: January 25th-29th
  - Release week: February 1-5th
* Will be ripping out st2resultstracker code
* @nmaludy and @amanda11 to follow up on any Python 3 on RHEL 7 issues
* @blag will follow up on pip and virtualenv upgrades
* The StackStorm/st2web#759 PR needs to add/update copyright headers on all files
  - @armab Will help update copyright header template
  - @m4dcoder Will write blog post on the contribution

## Organization/Partnership Proposal ##

* Short term fix will be implemented - @m4dcoder
  - Separate sections for system integrators and "vendors"
  - [Linux Foundation Insights page](https://insights.lfx.linuxfoundation.org/projects/stackstorm/dashboard)
* Long term fix still needs to be worked out - @dzimine
  - Map individual contributors to their employers via email address domain or GitHub organization membership
  
## ChatOps Roadmap ##

* Currently [on hold](https://github.com/StackStorm/discussions/issues/56) while we wait for MS Teams support in OpsDroid (opsdroid/opsdroid#1679) - thank you @cognifloyd for keeping an eye on this
* For context, please see the ChatOps discussion page: StackStorm/discussions#56
* @blag - Reach out to OpsDroid developer to discuss promoting each other in README files?

## StackStorm Expenses and Donate Button in st2web ##

 * @blag - Follow up with Packagecloud on converting package repository over to the free open source plan
 * @punkrokk and his company are generously sponsoring the project costs for all of 2021 so we can avoid adding the Donate button to st2web
   - HOWEVER, we need to still try to reduce costs where we can

## TSC Chairperson ##

* Moved to next month's TSC discussion

**Comment by copart-jafloyd** [comment]
> @blag - Reach out to OpsDroid developer to discuss promoting each other in README files?

I just sent this to the OpsDroid maintainers. This is the response from @jacobtomlinson, BDFL of OpsDroid:
> Awesome that's exciting!
> I'm in favour of that.

**Comment by cognifloyd** [comment]
I just sent this to the OpsDroid maintainers.
> @blag - Reach out to OpsDroid developer to discuss promoting each other in README files?

This is the response from @jacobtomlinson, BDFL of OpsDroid:
> Awesome that's exciting!
> I'm in favour of that.

**Comment by cognifloyd** [comment]
FYI https://github.com/opsdroid/opsdroid/pull/1679 was just merged, so the next OpsDroid release (next month) should include teams support.
