### ISSUE TITLE
TSC Meeting (2 Feb 2021): TSC Chair follow-up, v3.4.0 Release, Partners, Expenses

### ISSUE THREAD

**Issue by arm4b** [StackStorm/discussions#62]
February @StackStorm/tsc `1 hour` meeting will take place on Tuesday, `2nd Feb 2021, 09:30 AM US Pacific`.
See #33 for more info about how to join.

## Meeting Agenda
- Project updates:
  - New Contributors: https://github.com/StackStorm/st2/pull/5115 (Starbucks) https://github.com/StackStorm/st2/pull/5114 (Orchestral)
  - LF Contributions Analytics data: https://insights.lfx.linuxfoundation.org/projects/stackstorm/dashboard
- TSC Chairperson follow-up https://github.com/StackStorm/st2/pull/5071 and https://github.com/StackStorm/st2/pull/5135
  - TSC Chair definition, responsibilities, [Governance.md](https://github.com/StackStorm/st2/blob/master/GOVERNANCE.md#maintainer-roles) structure, roles, models.
- StackStorm [`v3.4.0`](https://github.com/orgs/StackStorm/projects/19) Release:
  - Release Manager @blag, Release Assistant: @amanda11
  - Target Date: ~end of January 2021~ mid February 2021?
    - blocker: Security update for `st2web` dependencies
  - NEW: Python 2.7 support in StackStorm Exchange @blag https://github.com/StackStorm/discussions/issues/40
- Rightsizing TSC Contribution Expectations (@punkrokk )
- Follow-up: StackStorm Partners (Ravi and @punkrokk )
- Follow-up: [StackStorm infra Expenses](https://github.com/StackStorm/discussions/issues/36) migration from Extreme to StackStorm
  -  Packagecloud, CircleCI, Forum, G Suite, AWS

cc @StackStorm/maintainers @StackStorm/contributors.

**Comment by blag** [comment]
Added a discussion about Python 2.7 support for Exchange packs to the agenda.

**Comment by arm4b** [comment]
Notes Based on the TSC Meeting:

## Attendees
- @StackStorm/maintainers (6/9): @m4dcoder @blag @armab @amanda11 @punkrokk @mickmcgrath13 
- @StackStorm/contributors: @jjm

Thanks everyone for joining!

## Meeting Minutes

## LF Analytics
  - Updated https://insights.lfx.linuxfoundation.org/projects/stackstorm/dashboard provides analytics about the technical contributions to the project.
  - Shows aggregated data everyone can use and see for tracking the impact from the partners and maintainers.
  - Close work with the LF Support allowed to manually tie the contributions with the companies/users profiles. Fixed: Ammeon, Orchestral partner contributions.
  - [Community Contributions Leaderboard](https://insights.lfx.linuxfoundation.org/projects/stackstorm/active-contributor?time=%7B%22from%22:%22now-90d%22,%22type%22:%22datemath%22,%22to%22:%22now%22%7D): filter by "all" can be used to track an aggregated contribution data: not just lines of code, but triaged Issues, Opened, Closed PRs, Reviews, etc.
  - TSC Maintainer responsibilities are described in the Governance https://github.com/StackStorm/st2/blob/master/GOVERNANCE.md#maintainer-responsibilities and it's a reminder for Maintainers to keep their level of involvement with the requirements they signed for when joined the TSC. 
  - @punkrokk raised a question about acknowledging non-technical contributions to the project.

## Partners
  - As partners are now disconnected from the requirement of being a TSC Member (based on previous Meeting per @dzimine call), entry criteria for both groups might differ and we may see folks that fit Partners based on their impact, but not the TSC Maintainers and vice-versa. Partners requirements TBD.
  - Community needs to find the balance/intersection between the Partner's & Open Source interests to ensure the healthy ongoing project growth under the Linux Foundation Governance.
  - Partners expressed the intent to form a new committee inside the StackStorm Governance to influence the non-technical project decisions.
  - @punkrokk (Blue Cycle) and Ravi (Orchestral) to provide a written proposal around the StackStorm Partners for Community to review and provide feedback.

## StackStorm v3.4.0 Release
  - v3.4.0 roadmap/TODO is 99% finished
  - Release Managers are close to starting the Community Pre-Release Testing
  - Blocker: st2web security update due to outdated dependencies
     - Solution WIP by Orchestral contribution: https://github.com/StackStorm/st2web/pull/854 
  - Problem: Python 2 CI in StackStorm-Exchange started to fail
     - Consensus Plan:
       - Drop Python 2 support for Exchange in this v3.4 release (initial intent was to support it until v3.5)
       - Remove Python 2 Tests from all the packs CI
       - Set the py3 as the only supported version in the pack metadata
       - Add Changelog for every pack about py2 removal
       - Bump the major version for every pack
       - Automate it as a st2 github bot (commits to `master`)
       - Announce to Community the deprecation of Python 2 in Exchange

## Uncovered
- TSC Chair Election Process & Procedures: https://github.com/StackStorm/st2/pull/5071 and https://github.com/StackStorm/st2/pull/5135
  - Moved to the next TSC meeting, due to missing @dzimine
- Next meeting will be focused on the `v3.5.0` Roadmap Planning.
