### ISSUE TITLE
TSC Meeting (2 Mar 2021): Finalizing v3.4.0, v3.5.0 Roadmap Planning, Partnership Program

### ISSUE THREAD

**Issue by arm4b** [StackStorm/discussions#67]
March 2021 @StackStorm/tsc `1 hour` meeting ~will take~ took place on Tuesday, `2nd Mar 2021, 09:30 AM US Pacific`.
See #33 for more info about how to join.

## Meeting Agenda
- Finalizing the StackStorm `v3.4.0` release *(10min)*
  - Release Manager @blag, Release Assistant: @amanda11
  - Pre-Release Testing: https://github.com/StackStorm/discussions/issues/66
- StackStorm `v3.5.0` Roadmap planning *(25min)*
  - Target date: (3mo)?
  - Release Manager: @amanda11 (based on [release rotation](https://github.com/StackStorm/discussions/wiki/Release-Management-Rotation)).
  - Release Assistant: WHO @StackStorm/maintainers ?
  - What was @StackStorm/tsc impact in `v3.4.0` and what are individual @StackStorm/maintainers plans for `v3.5.0`?
  - [Roadmap WIP](https://github.com/orgs/StackStorm/projects/20)
- StackStorm Partners Program *(15min)*
  - https://stackstorm.com/partners/
  - https://stackstorm.com/partners-program/
  - [[RFC] How to become a StackStorm Partner?](https://github.com/StackStorm/discussions/issues/64)
  - Plan: discuss #64, bootstrap and announce the program to the public
- Follow-up: [StackStorm infra Expenses](https://github.com/StackStorm/discussions/issues/36) *(5min)*
  - Incident: PackageCloud.io repository account suspension on `24th Feb`, paid plan/traffic st2 can't afford (#36)
    - Discuss and Plan the migration to alternative solutions
  - AWS account ownership Migration (@punkrokk -> @dzimine)
- Any other random Questions and Discussions *(5min)*

### Attendees:
- `~20` Attendees total
- Host: @armab
- @StackStorm/maintainers: @dzimine @Kami @blag @m4dcoder @amanda11 @nmaludy @punkrokk 
- @winem @nzlosh @cognifloyd @guzzijones

### Finalizing the StackStorm `v3.4.0` release
  - Release Manager @blag, Release Assistant: @amanda11
  - Pre-Release Testing: https://github.com/StackStorm/discussions/issues/66
  - Last-minute fixes: ~st2ctl register-recreate flag~, ~security blocker~, ~RabbitMQ EL8 fix~.
  - No other blockers, the Release Team @blag @amanda11 is planning to start the Release Automation this week.
  - Release Announcement TBD after that.
### StackStorm `v3.5.0` Roadmap planning
  - Decided Target date: `June 2021`
  - Project Roadmap: https://github.com/orgs/StackStorm/projects/20
  - Release Manager: @amanda11
  - Release Assistant TBD from the @StackStorm/maintainers (based on [release rotation](https://github.com/StackStorm/discussions/wiki/Release-Management-Rotation)).
  - [Roadmap WIP](https://github.com/orgs/StackStorm/projects/20)
    - https://github.com/StackStorm/discussions/issues/68 Add Python `v3.8` support to `st2` (@nzlosh and @winem to compose first WIP PR, team assisting & helping next)
      - TBD: [Add `Ubuntu 20.04 LTS` support (packages)](https://github.com/orgs/StackStorm/projects/12)
        - TBD: Drop Ubuntu 16.04 LTS
    - Core Performance Improvements - @Kami
    - [Add `Redis` as a required coordination backend](https://github.com/StackStorm/st2/pull/5052) in st2 core - @m4dcoder
      - Ansible Deployment - @amanda11 
      - Puppet Deployment - @nmaludy 
      - Docker & K8s - Done
    - PIP & Virtualenv Maintenance upgrade - @amanda11 
    - Discussion, Research, and Proposal about switching to [Poetry](https://pypi.org/project/poetry/) for st2 core dependencies (@cognifloyd will research and create a GH Discussion, @nmaludy advising). 
    - NO OWNERS: Switching the st2 Integration Tests from TravisCI to GH Actions (best) or at least CircleCI.
    - Other TSC Members: @mickmcgrath13 and @punkrokk have to find a way to contribute technically, as there were no contributions or commitments for the past releases (several months). 
### StackStorm Partners Program
  - WIP: https://stackstorm.com/partners/
  - WIP: https://stackstorm.com/partners-program/
  - WIP: [[RFC Discussion] How to become a StackStorm Partner?](https://github.com/StackStorm/discussions/issues/64)
  - @punkrokk presented the table highlighting different kind of partners and their potential interest
  - Some really good conversation is happening around the Partners Program
  - Team feedback is to keep it simpler, minimize the burden in maintaining the program
  - @punkrokk and Ravi will post their findings and proposals in the Github Discussion: #64 for the community to review/discuss more
  - Future Plan:
    - once consensus is reached, bootstrap it, link to the partners page from the main website, announce the program to the public and ST2 Community (Slack, Twitter, LinkedIn, Blog, Website) and start sending some traffic.
    - place a visits counter on the https://stackstorm.com/partners/ page to have visibility of how much traffic is present there.
### Other
  - StackStorm can't afford paid $ PackageCloud.io anymore for distributing deb/rpm packages to its community
  - PackageCloud.io transition to other solutions needs a dedicated technical GH/Slack Discussion and research
  - @cognifloyd will be organizing a meeting StackStorm + OpsDroid maintainers on `11 March 2021 at 16:30 UTC` to meet each other and maybe discuss the future of StackStorm ChatOps https://github.com/StackStorm/discussions/issues/8#issuecomment-786759072

cc @StackStorm/maintainers @StackStorm/contributors.

**Comment by cognifloyd** [comment]
In the meeting, please mention (no need to discuss, just announce) that there will be a StackStorm+OpsDroid cross community call on 11 March 2021 at 16:30 UTC: https://github.com/StackStorm/discussions/issues/8#issuecomment-786759072

**Comment by arm4b** [comment]
@cognifloyd Sounds good. Thanks for organizing that!
We'll also announce it in Community Twitter/LinkedIn :+1:  Just please ping me or @blag in a week of 11March (Monday is ideal) to make sure we don't miss publishing it.

**Comment by Kami** [comment]
From my side, the main topic is performance improvements related changes (https://github.com/StackStorm/st2/pull/4846, https://github.com/StackStorm/st2/pull/5153). Maybe that can also be the main topic of the next release.

I may have some scheduling conflicts with that time slot, but will try my best to attend.

**Comment by blag** [comment]
The meeting is currently running, but we should also add moving our integration tests away from Travis-CI to our TODO list.

**Comment by arm4b** [comment]
@blag +100. Can you please document that as a new issue for the `v3.5.0` Roadmap (https://github.com/orgs/StackStorm/projects/20)?

**Comment by blag** [comment]
Done. :+1:

**Comment by arm4b** [comment]
## Meeting Minutes:

### Attendees:
- `~20` Attendees total
- Host: @armab
- @StackStorm/maintainers: @dzimine @Kami @blag @m4dcoder @amanda11 @nmaludy @punkrokk 
- @winem @nzlosh @cognifloyd @guzzijones

### Finalizing the StackStorm `v3.4.0` release
  - Release Manager @blag, Release Assistant: @amanda11
  - Pre-Release Testing: https://github.com/StackStorm/discussions/issues/66
  - Last-minute fixes: ~st2ctl register-recreate flag~, ~security blocker~, ~RabbitMQ EL8 fix~.
  - No other blockers, the Release Team @blag @amanda11 is planning to start the Release Automation this week.
  - Release Announcement TBD after that.
### StackStorm `v3.5.0` Roadmap planning
  - Decided Target date: `June 2021`
  - Project Roadmap: https://github.com/orgs/StackStorm/projects/20
  - Release Manager: @amanda11
  - Release Assistant TBD from the @StackStorm/maintainers (based on [release rotation](https://github.com/StackStorm/discussions/wiki/Release-Management-Rotation)).
  - [Roadmap WIP](https://github.com/orgs/StackStorm/projects/20)
    - https://github.com/StackStorm/discussions/issues/68 Add Python `v3.8` support to `st2` (@nzlosh and @winem to compose first WIP PR, team assisting & helping next)
      - TBD: [Add `Ubuntu 20.04 LTS` support (packages)](https://github.com/orgs/StackStorm/projects/12)
        - TBD: Drop Ubuntu 16.04 LTS
    - Core Performance Improvements - @Kami
    - [Add `Redis` as a required coordination backend](https://github.com/StackStorm/st2/pull/5052) in st2 core - @m4dcoder
      - Ansible Deployment - @amanda11 
      - Puppet Deployment - @nmaludy 
      - Docker & K8s - Done
    - PIP & Virtualenv Maintenance upgrade - @amanda11 
    - Discussion, Research, and Proposal about switching to [Poetry](https://pypi.org/project/poetry/) for st2 core dependencies (@cognifloyd will research and create a GH Discussion, @nmaludy advising). 
    - NO OWNERS: Switching the st2 Integration Tests from TravisCI to GH Actions (best) or at least CircleCI.
    - Other TSC Members: @mickmcgrath13 and @punkrokk have to find a way to contribute technically, as there were no contributions or commitments for the past releases (several months). 
### StackStorm Partners Program
  - WIP: https://stackstorm.com/partners/
  - WIP: https://stackstorm.com/partners-program/
  - WIP: [[RFC Discussion] How to become a StackStorm Partner?](https://github.com/StackStorm/discussions/issues/64)
  - @punkrokk presented the table highlighting different kind of partners and their potential interest
  - Some really good conversation is happening around the Partners Program
  - Team feedback is to keep it simpler, minimize the burden in maintaining the program
  - @punkrokk and Ravi will post their findings and proposals in the Github Discussion: #64 for the community to review/discuss more
  - Future Plan:
    - once consensus is reached, bootstrap it, link to the partners page from the main website, announce the program to the public and ST2 Community (Slack, Twitter, LinkedIn, Blog, Website) and start sending some traffic.
    - place a visits counter on the https://stackstorm.com/partners/ page to have visibility of how much traffic is present there.
### Other
  - StackStorm can't afford paid $ PackageCloud.io anymore for distributing deb/rpm packages to its community
  - PackageCloud.io transition to other solutions needs a dedicated technical GH/Slack Discussion and research
  - @cognifloyd will be organizing a meeting StackStorm + OpsDroid maintainers on `11 March 2021 at 16:30 UTC` to meet each other and maybe discuss the future of StackStorm ChatOps https://github.com/StackStorm/discussions/issues/8#issuecomment-786759072

cc @StackStorm/maintainers @StackStorm/contributors.
