### ISSUE TITLE
Plan: Remove support for Ubuntu 16.04 (Xenial)

### ISSUE THREAD

**Issue by amanda11** [StackStorm/discussions#69]
Once Ubuntu 20.04 support has been added (https://github.com/StackStorm/discussions/issues/68), then we should remove support for Ubuntu 16.

> <b>Good first issues!</b>
> Removing is easy. If someone from the community wants to help with these tasks, this is a great way to help us with the `v3.5.0` release activities. Feel free to ask questions here or in our `#development` [Slack channel](https://stackstorm.com/#community). 

Checklist:

- [x] st2
  - [x] CI/CD - https://github.com/StackStorm/st2/pull/5283
  - [x] to be determined
  - [x] identify and close all the U16 associated issues
- [x] st2web - amanda11
  - [x] CI/CD
- [x] st2chatops - ~@amanda11
  - [x] CI/CD
  - [x] deb scriptlets
  - [x] Dockerfile
- [x] st2-packages - @amanda11 - https://github.com/StackStorm/st2-packages/pull/704
  - [x] remove from packages
  - [x] remove from bash installer
  - [x] CI/CD
  - [x] docker-compose
- [x] st2packaging-dockerfiles
  - [x] U16 Dockerfiles - @amanda11 
- [x] ansible-st2
  - [x] remove any Xenial specific checks
  - [x] remove from integration runs
- [x] puppet-st2 - @rush-skills
  - [x] CI/CD
  - [x] OS support
- [x] st2ci - @amanda11 
  - [X] - pre-release
  - [x] - release
- [x] stcd - @amanda11
- [x] st2docs - https://github.com/StackStorm/st2docs/pull/1074
  - [x] remove as a supported install / upgrade OS
  - [x] Roadmap update
- [x] st2vagrant - https://github.com/StackStorm/st2vagrant/pull/48
- [x] ~st2docker - move from xenial to focal~ st2-docker is based on `bionic`

**Comment by winem** [comment]
I'm currently working on the support for Ubuntu 20.04 in ansible-st2 and will remove the support for 16.04 at the same time. This is already in progress and I'm close to provide the PRs. 

I can also take care of the st2docs topics.

**Comment by rush-skills** [comment]
Can update puppet-st2 work completed in this issue too :)
