### ISSUE TITLE
Plan: Deploy redis as co-ordination backend

### ISSUE THREAD

**Issue by amanda11** [StackStorm/discussions#70]
Plan for all the repos that will need updating for using redis as default as a co-ordination backend.

- [X] st2 - https://github.com/StackStorm/st2/pull/5226
- [x] st2-packages - bash installer https://github.com/StackStorm/st2-packages/pull/698 @m4dcoder 
- [x] ansible-st2 - https://github.com/StackStorm/ansible-st2/pull/296 @amanda11 
- [x] puppet-st2 - @rush-skills
- [x] st2docs @m4dcoder 
- [X] st2.conf default to redis coordination url in package (see comment on ansible-st2 PR) -https://github.com/StackStorm/st2/pull/5262

**Comment by rush-skills** [comment]
We can mark puppet-st2 as complete and close this one too

**Comment by arm4b** [comment]
That's really nice!

Thanks @rush-skills for the follow-up :+1:
