### ISSUE TITLE
TSC Vote: StackStorm Partnership Program

### ISSUE THREAD

**Issue by arm4b** [StackStorm/discussions#72]
Following almost 1 year of discussions, more than 6 [TSC Meetings](https://github.com/StackStorm/discussions/labels/TSC%3Ameeting), consultations with the Partners, discussions with the LF, and additional approval from the LF Legal I'd like to invite @StackStorm/tsc to vote on approving the StackStorm Partnership program.

### The plan:

- 1 Terms and conditions of the Partnership Program are described at https://stackstorm.com/partners-program/
- 2 List of the Partners, each tagged with several categories, as shown and designed on the https://stackstorm.com/partners/
  - 2.1 We'll generate a randomized order for the Partners list for the fair visibility distribution (per @raviorch Orchestral feedback)
- 3 We'll place a traffic stats counter at the Partner page to indicate the number of hits/visits page is getting for the partner's page traffic indicator (per @punkrokk feedback)
- 4 We'll create a new section linking to the Parners page from the main StackSorm.com website
  - 4.1 New block "Supported by the Partners" will be placed before the "Used by Your Peers" and would include the Partners logos + Partners page link
- 5 To be listed on the page, Partners will have to accept their participation and agreement with the terms as described at https://stackstorm.com/partners-program/ (per @punkrokk initial question about the Legal Agreements and then LF Legal consultation feedback)
- 6 We'll launch and announce the program to Community via Blog Post and channels: Slack, Twitter, Newsletter, LinkedIn

![StackStorm_Partners_Program_–_Description_-_StackStorm_-_2021-04-02_18 56 42](https://user-images.githubusercontent.com/1533818/113441018-666ac800-93e5-11eb-9bc6-e028f45aabbb.png)

Additional sub-committees, multi-level tiers of the programs and are outside of this scope and could be discussed and progressed in future iterations. 

Related Discussions:
* [ [RFC] How to become a StackStorm Partner? #64 ](https://github.com/StackStorm/discussions/issues/64)
* [RFC: StackStorm Partners, Code of Conduct and Economy #51](https://github.com/StackStorm/discussions/issues/51)

----

@StackStorm/tsc Voting period per [Governance](https://github.com/StackStorm/st2/blob/master/GOVERNANCE.md#how-decisions-are-made) is 1 week and needs a majority of votes from the TSC voting pool to approve.

**Comment by arm4b** [comment]
+1

**Comment by Kami** [comment]
I'll abstain at this point (aka +0) since I don't think I added much of value to those discussions.

**Comment by amanda11** [comment]
Before voting, some grammar points on: https://stackstorm.com/partners-program/

- "We welcome everyone to help and support the project is it maintenance" - not sure about the "is it ...", should it be "be it"
- The link to policies at bottom seems a bit on its own, just after the Contact Us

The removal/addition of companies to partners page "StackStorm or the partner may choose to end the partnership at any time". Does "StackStorm" here have a defined meaning, is this by majority vote of StackStorm TSC? 

Interested in discussing if indemnification clause is needed at TSC meeting.

**Comment by raviorch** [comment]
Agreed; before voting IMHO, we need to set some ground rules for the 
partners page:
As of today there is no link to the partners page from the main page 
http://stackstorm.com, need to first add that
On the partner landing page have a list of current partners and also 
have a “How To Become A Partner” section
In the “How To Become A Partner” page also highlight what the project 
will give back to the partner more clearly as the current 1 paragraph is 
not very descriptive
The contributions should be categorized as per the function, right now 
in the proposed page it is very ambiguous
I would also like to ask the team to consider the badge system I 
proposed, if not being adopted, propose a mechanism that would provide 
differentiation between partners based on the contributions
Only after these are addressed is the Partner Page agenda item is ready 
to vote.

Regds
Ravi

------ Original Message ------
From: "Amanda McGuinness" ***@***.***>
To: "StackStorm/discussions" ***@***.***>
Cc: "raviorch" ***@***.***>; "Mention" 
***@***.***>
Sent: 4/6/2021 8:54:37 AM
Subject: Re: [StackStorm/discussions] TSC Vote: StackStorm Partnership 
Program (#72)

**Comment by blag** [comment]
It sounds like we need to take this discussion to a subcommittee.

@raviorch Can you also officially create your own proposal of exactly what you think the partners program should look like?

**Comment by raviorch** [comment]
Can absolutely do it, will work with the team to create a subcommittee 
and move forward.
Ravi
------ Original Message ------
From: "blag" ***@***.***>
To: "StackStorm/discussions" ***@***.***>
Cc: "raviorch" ***@***.***>; "Mention" 
***@***.***>
Sent: 4/6/2021 9:32:23 AM
Subject: Re: [StackStorm/discussions] TSC Vote: StackStorm Partnership 
Program (#72)

>
>It sounds like we need to take this discussion to a subcommittee.
>
***@***.*** <https://github.com/raviorch> Can you also officially create

**Comment by punkrokk** [comment]
I also believe we need to have a subcommittee to flush this out.

**Comment by mickmcgrath13** [comment]
Subcommitte issue started here:
https://github.com/StackStorm/discussions/issues/73

**Comment by arm4b** [comment]
Closing as not approved by the TSC after 7 days of the voting period.

TSC Meeting Decision (https://github.com/StackStorm/discussions/issues/71) was to continue the discussion in https://github.com/StackStorm/discussions/issues/73. Partners sub-committee has to re-iterate on the program and come up with a proposal for the next (May) TSC Meeting.
Another Discussion should be created for the StackStorm TSC to Vote.
