### ISSUE TITLE
TSC Subcommittee Meeting (22 Apr 2021): Migrate forum.stackstorm.com

### ISSUE THREAD

**Issue by blag** [StackStorm/discussions#75]
April 2021 @StackStorm/tsc `1 hour` meeting will take place on Thursday, `22th Apr 2021, 09:30 AM US Pacific`.
See #33 for more info about how to join.

# Agenda #

## Migrating forum.stackstorm.com ##

* We're on 50% FOSS plan for forum.stackstorm.com for Discourse
  - Consider switching to self-hosted Discourse (free, maintenance burden)
  - Consiser switching to GH Discussions (free, zero maintenance, integrates with our GH community)
* Keep SEO in mind
* Owner + 1 needed to: research, propose a plan, execute the migration

# Deliverables #

* [ ] A plan to migrate to the new discussion host provider
* [ ] A plan (or not) for what to do with the old Discourse forums (forum.stackstorm.com)
* [ ] A delegate responsible for overseeing the migration
  - [ ] Need greater access on GitHub?
  - [ ] Need access to credentials in 1Password?
* [ ] A timeline for the work to be done

**Comment by blag** [comment]
* [x] [Discourse's free program](https://free.discourse.group) will not work for us because we cannot use our own `forum.stackstorm.com` subdomain
* [ ] Investigate migrating to the self-hosted version of Discourse
* [x] Enabling GitHub Discussions in `st2` repository - @armab
* [x] Turn on a banner in the Discourse forums to direct people to post in the new GitHub Discussions
* [ ] Investigate exporting all current posts (called "topics") on the forum to GitHub Pages
  - [ ] Write and run script to dump current topics to a format that GitHub Pages can read
  - [ ] Ensure current topic links don't break (eg: `forum.stackstorm.com/t/<topic_slug>/<topic_id>`)
    + [ ] Repository named `t` so the GitHub Pages site is at `stackstorm.github.io/t`
    + [x] Use DNS to redirect `forum.stackstorm.com` to `stackstorm.github.io`
    + [x] So all current topic links would still be the same
    + [x] Would lose out on user profile links (eg: `forum.stackstorm.com/u/...`)

Current plan (assuming all investigations pan out):

* Start using GitHub Discussions in `st2` repository
* Make current Discourse forums read-only
* Migrate forums posts/topics to GitHub Pages (with a repository named `t`)
* Use DNS to point `forum.stackstorm.com` to `stackstorm.github.io` for backwards compatibility

**Comment by arm4b** [comment]
The Github Q/A was set up at: https://github.com/StackStorm/st2/discussions
Feel free to adjust, edit or add any new Categories. 

It's interesting that it's possible to convert an existing `Issue` to a `Question`.
Example: https://github.com/StackStorm/st2/issues/5181

We could do that for a bunch of other existing StackStorm Issues: https://github.com/StackStorm/st2/labels/question

**Comment by blag** [comment]
Thanks for taking care of that!

Yeah, it will be much nicer to separate questions and discussions out from feature requests and bug reports. 😄

**Comment by punkrokk** [comment]
For the future: https://letswp.io/download-discourse-forum-wget/

**Comment by arm4b** [comment]
Superseded by the https://github.com/StackStorm/discussions/issues/89 plan.
