### ISSUE TITLE
TSC Vote: StackStorm Partnership Program - revised

### ISSUE THREAD

**Issue by mickmcgrath13** [StackStorm/discussions#80]
# Goals
To align incentives for the StackStorm project as well as partners

# The Plan
Officially launch the new Partner Program details.

1. Terms and conditions of the Partnership Program are described in a draft at https://stackstorm.com/stackstorm-partners-program-description/?preview=true (will be moved to https://stackstorm.com/partners-program/)
2. List of the Partners, each tagged with several categories, as shown and designed on the partners program TOC page
3. We'll place a traffic stats counter at the Partner page to indicate the number of hits/visits page is getting for the partner's page traffic indicator
4. We'll create a new section linking to the Partners page from the main StackSorm.com website
5. We'll launch and announce the program to Community via Blog Post and channels: Slack, Twitter, Newsletter, LinkedIn

# Details
This involves making the draft page live, adding labels to existing partners, and ensuring the submission email is ready.

Potential partners will email `partners@stackstorm.com` with a proposal for partnership.  Upon approval, partners will be consulted on which labels to put beside their name on [the partners page](https://stackstorm.com/partners/), and the labels will be added accordingly

The labels will be driven by the *headers* of the table in the [partner program page](https://stackstorm.com/stackstorm-partners-program-description/?preview=true) (i.e. `wrench: engineering, handshake: proserve, briefcase: bizdev, rocket: marketing`)

## Draft
The draft is here
https://stackstorm.com/stackstorm-partners-program-description/?preview=true

## Example Partner Labels
An example of the partner page labels is here:
https://stackstorm.com/partners/ (see Bitovi's entry):
![image](https://user-images.githubusercontent.com/1030325/120481138-6c454100-c375-11eb-98d9-e28c60c444c9.png)
![image](https://user-images.githubusercontent.com/1030325/120481151-7109f500-c375-11eb-9116-93614f06c00c.png)

## Implementation Discussion
Closes https://github.com/StackStorm/discussions/issues/73

## Original Proposal
Closes https://github.com/StackStorm/discussions/issues/72

# Next Steps
- Upon approval via TSC vote, the draft page will be made live by swapping the urls for [the temporary draft url](https://stackstorm.com/stackstorm-partners-program-description/?preview=true) to the [official permanent url](https://stackstorm.com/partners-program/)
- All existing partners will be consulted on which labels to put beside their name on [the partners page](https://stackstorm.com/partners/), and those icons will be added accordingly
    - The labels will be driven by the *headers* of the table in the [partner program page](https://stackstorm.com/stackstorm-partners-program-description/?preview=true) (i.e. `wrench: engineering, handshake: proserve, briefcase: bizdev, rocket: marketing`)
- ensure `partners@stackstorm.com` is set up
- Create link to partners page from main site

# Screenshots
![image](https://user-images.githubusercontent.com/1030325/120481307-9565d180-c375-11eb-8ada-7fd25cf8dd9d.png)
![image](https://user-images.githubusercontent.com/1030325/120481336-a0206680-c375-11eb-82c9-e6eabd6b6782.png)

For more details on voting, see: https://github.com/StackStorm/st2/blob/master/GOVERNANCE.md#how-decisions-are-made

**Comment by mickmcgrath13** [comment]
@armab Can you confirm whether or not `partners@stackstorm.com` is set up?

**Comment by arm4b** [comment]
@mickmcgrath13 Yep, it works

**Comment by arm4b** [comment]
+1 for the revised Partnership Program version.

**Comment by Kami** [comment]
+1

**Comment by blag** [comment]
👍

**Comment by mickmcgrath13** [comment]
👍  on this :)

**Comment by nmaludy** [comment]
+1

**Comment by amanda11** [comment]
+1 - under the assumption that the new layout is like the Bitovi example as shown, e.g. the sub-headings are staying, but we're  adding in the partnership contribution labels as documented on the partnership program page.
(I think that's what the proposal is... - but just wanted to clarify!)

**Comment by mickmcgrath13** [comment]
@amanda11 It'd be like the screenshots under "Example Partner Labels", yes.  Only additive changes to the partners list :)

**Comment by punkrokk** [comment]
+1

**Comment by m4dcoder** [comment]
+1

**Comment by winem** [comment]
+1

**Comment by mickmcgrath13** [comment]
This is complete!

**Comment by mickmcgrath13** [comment]
- stackstorm.com
- stackstorm.com/partners
- https://stackstorm.com/partners-program/

**Comment by arm4b** [comment]
Thanks a lot @mickmcgrath13 for the lead coordinating and shipping the Partners Program! :+1:
