### ISSUE TITLE
TSC Meeting (03 Aug 2021): v3.6 Roadmap Planning, Chatops, Maintenance, Governance

### ISSUE THREAD

**Issue by arm4b** [StackStorm/discussions#85]
August 2021 @StackStorm/tsc `1 hour` meeting will take place on Tuesday, `03 Aug 2021, 09:30 AM US Pacific`.
See #33 for more info about how to join.

## Meeting Agenda

- Faster StackStorm Releases (@punkrokk) (#84) *(7min)*
- StackStorm `v3.6.0` Roadmap planning *(15min)*
  - Target date: ?
  - Release Manager: @winem (based on [release rotation](https://github.com/StackStorm/discussions/wiki/Release-Management-Rotation)).
  - Release Assistant: WHO @StackStorm/maintainers?
  - What was @StackStorm/maintainers and partners impact in `v3.5.0`?
  - What are @StackStorm/maintainers and partners plans for `v3.6.0`?
  - [Roadmap WIP](https://github.com/orgs/StackStorm/projects/22)
- ChatOps: Node.js -> Python transition (@cognifloyd) *(7min)*
- [StackStorm Infra & Expenses](https://github.com/StackStorm/discussions/issues/36) *(10min)*
  - Packagecloud vs CloudSmith FOSS plan (#74)
  - Infra/Maintenance: stackstorm.com website migration to static pages #76
  - Infra/Maintenance: Forum -> Github Discussions migration #75
- Relaxing ST2 Governance for Maintainers (@blag) *(15min)*
- Any other random Questions and Discussions *(5min)*

**Comment by guzzijones** [comment]
Let me preface this by saying I would like to be a partner in some way.  I believe there should be some sort of membership cost to be a partner.  This will help fund the core TSC.

**Comment by arm4b** [comment]
## Participants
Host: @armab
Attendees: @blag @amanda11 @winem @m4dcoder @guzzijones @cognifloyd


## Meeting Minutes
### StackStorm v3.5.0 release outcomes:
- @guzzijones noted a big performance improvement impact from running the latest st2 v3.5.0 in prod
- @userlocalhost from the `#community-japan` shared in Slack the v3.5.0 performance graphs based on some test workflows. Slides: https://www.slideshare.net/Hiroyasu-OHYAMA/verification-of-performance-improvement-of-stackstorm-v35 (credit to @Kami for this great achievement! :tada:)
- Thanks again @amanda11 and @winem for shipping the massive v3.5.0 as Release managers

### Faster StackStorm Releases  https://github.com/StackStorm/discussions/issues/84
- Q: How to make releases easier and faster?
  - how about weekly/on-demand releases when needed?
- Improvements to the release process (https://github.com/StackStorm/discussions/wiki/Release-Process):
  - remove the "manual testing" stage (currently blocks 1 week)
  - we need to commit to the date, more preparation and planning work
  - include in the current release what was completed
    - move to the next roadmap something that wasn't finished to avoid blocking the release date
    - security patches and version updates (?) blocked 2 releases
- The team is good with the 3mo release cadence standard so far:
  - predictable, stable, widely used by the other projects 

### StackStorm v3.6.0 Roadmap planning
- Release Manager: @winem 
- NEW release Assistant (confirmed): @guzzijones 
- Target date: October 2021
  - Updated https://github.com/StackStorm/discussions/wiki/Release-Management-Rotation with the schedule and release managers
- Team to help where they can during the process and release preparation
- Maintenance release: just ship what was contributed: improvements, fixes, no major features planned to land from the team in this release

### ChatOps: Node.js -> Python transition
- @cognifloyd shared the news that MSTeams PR was merged from the OpsDroid side
  - The ball is on the StackStorm side now
- TODO: @cognifloyd to create a Github Discussion (or update old one) with the plans, blockers, and corner cases related to the st2chatops implementation with the https://github.com/opsdroid/opsdroid
- @blag @winem @amanda11 looking forward to helping where they can

### StackStorm Infra & Expenses
#### AWS
  - We're on AWS FOSS plan now (thanks to @punkrokk)
  - Switched st2 e2e CI from nightly to weekly builds (thanks to @amanda11) 
    - TODO @armab: Check the AWS usage impact (reduced by how much?)
  - Didn't switch to EC2 spot instances yet (TODO by @punkrokk per previous TSC meeting #83)
#### Packages Hosting Solution (deb/rpm)
  - We're on the PackageCloud paid plan now (costs ~$120/mo)
  - Hidden complexity of moving to other deb/rpm provider: rework st2cicd workflows, create new st2 integration pack, releases, st2cicd, update users with the new URL, etc
  - Agreed Actionable items:
    - Switch to the PackageCloud FOSS plan to start saving `$` ASAP
      - TODO @winem to finish the deb/rpm packages cleanup ([Screenshot](https://user-images.githubusercontent.com/1533818/125513492-6a406280-7fdb-4b48-a31e-79f6cdbd9e40.png))
    - Discover the CloudSmith features and run the research with pros/cons
      - TODO @cognifloyd will start looking at the CloudSmith solution and discovery
    - TODO @blag will lead the Partnership communication
      - We now have an official Partners program, yay! (https://stackstorm.com/partners/)

### Relaxing ST2 Governance for Maintainers
  - Problem: The requirements to join the TSC and become a StackStorm Maintainer are too high, being a blocker for the new community members to join as official TSC members
  - https://github.com/StackStorm/st2/blob/master/GOVERNANCE.md#how-to-become-a-maintainer
  - Proposed solution:
    - Remove `1 day/week` hard requirement from the Governance for TSC Maintainers, as something that doesn't work anymore
      - half of the TSC don't comply with the 1 day/week requirement anyway
