### ISSUE TITLE
CentOS 8 EOL end 2021

### ISSUE THREAD

**Issue by amanda11** [StackStorm/discussions#88]
As CentOS 8 reaches EOL at Dec 2021, with RH supporting CentOS 8 Stream afterwards, this discussion covers the changes required.
Discussed in Sept 2021 TSC meeting. Will use CentOS 8 for CI for 3.6, and move to RockyLinux or AlmaLinux during the 3.6 lifetime.

Plan:
- [X] Agree RockyLinux or AlmaLinx or Oracle Linux (Oct TSC meeting - agreed to target RockyLinux unless encounter issues)
- [x] st2ci/cd
  - [x] Replace CentOS 8 for PRs - https://github.com/StackStorm/st2cd/pull/469, https://github.com/StackStorm/st2ci/pull/206
  - [x] Replace CentOS 8 for E2E stable/unstable - not required - RHEL used rather than CentOS8 - no change required.
- [X] Replace CentOS 8 for CI runs on repos
  - [X ] st2 (@amanda11 - https://github.com/StackStorm/st2/pull/5552)
  - [X] st2-auth-ldap (no changes required)
  - [X] st2-rbac-backend (no changes required)
  - [x] st2web (no changes required)
  - [X] orquesta (no changes required)
- [x] st2docs - update roadmap and docs (install, upgrade, etc - any mention of CentOS 8).
- [x] st2packaging-dockerfiles  (@amanda11 - https://github.com/StackStorm/st2packaging-dockerfiles/pull/108)
- [x] st2-packages  - update to use new containers - @amanda11 (https://github.com/StackStorm/st2-packages/pull/711)
- [x] st2chatops - change to use rockylinux 8 containers (@amanda11 https://github.com/StackStorm/st2chatops/pull/171)
- [x] ansible-st2 - @amanda11 (https://github.com/StackStorm/ansible-st2/pull/308)
- [x] puppet-st2
- [x] st2vagrant - @amanda11 (https://github.com/StackStorm/st2vagrant/pull/50)

**Comment by amanda11** [comment]
Discussed in October TSC Meeting. Suggestion to try and build on Rocky Linux, and then to test built RPMs from RockyLinux on at least RockyLinux and RHEL 8 ( ideally on AlmaLinux and OracleLinux), to test whether RPMs built on RockyLinux will be compabile, or any issues found.

**Comment by amanda11** [comment]
Given that the st2packaging-dockerfiles I don't believe are version based, then we might need to keep the centos8 Dockerfile for the moment https://github.com/StackStorm/st2packaging-dockerfiles/tree/master/packagingbuild. 

For investigation we might need to do a PR on st2packaging-dockerfiles to generate the RockyLinux containers for build and test, and perform a manual build of the unstable RPM. We could I believe get the Dockercontainer's for both CentOS 8 and RockyLinux both being available, and then in a PR on st2-packages switch over from CentOS8 to RockyLinux for the main branch.

So I think a merge on st2packaging-dockerfiles to ADD RockyLinux containers would be the first step, and could be done without breakiing anything, but allow us to easily then generate RPMs from a st2-packages PR for testing.

**Comment by amanda11** [comment]
Any preferences for ansible-st2. Do we move to rockylinux8 for both the stable 3.6.0 and unstable 3.7.0 builds, or continue to use CentOS8 for the stable builds and rockylinux for unstable builds? I'm thinking perhaps move both over.

**Comment by winem** [comment]
I'd also prefer to move both to Rocky Linux.

**Comment by cognifloyd** [comment]
Yeah. CentOS 8 is dead. It's almost more important to get stable using Rocky Linux than it is to get unstable using it because it is dead dead. Let's move both.
