### ISSUE TITLE
Migrate forum.stackstorm.com to GitHub Discussions

### ISSUE THREAD

**Issue by winem** [StackStorm/discussions#89]
We decided to migrate forum.stackstorm.com to GitHub Discussions at https://github.com/StackStorm/st2/discussions

@armab already set the forum to read-only, archived it and added a banner on top of the page to inform users. Thank you! 

ToDos and things to discuss: 
- [x]  Organize categories & labels
- [x]  Manage and moderate questions & discussions 
  - [x]  Everyone from the TSC is welcome to moderate discussions. Do we need moderators to be contacted by the community members if something needs to be escalated? 
- [x]  convert forum.stackstorm.com to GitHub static pages so we won't loose SEO/traffic/URLs (https://github.com/StackStorm/forum.stackstorm.com)
- [x] cancel the Discourse billing $50/mo
- [x] switch `CNAME` from Discourse-hosted to GH Static pages 
- [ ] Migrate integrations
  - [ ] Slack integration to notify about new Questions / Discussions (https://stackstorm-community.slack.com/archives/C066APT88/p1630043814000600 )
  - [ ] Daily discussions agregator  to post a summary of new questions once a day ( https://stackstorm-community.slack.com/archives/CSBELJ78A/p1631028662011000 )
- [ ] Blog post to announce the migration
  - [ ] write the post
  - [ ] publish it on https://stackstorm.com/blog/

Extra info: 
- https://gist.github.com/mikecrittenden/fe02c59fed1aeebd0a9697cf7e9f5c0c seems to be super helpful to convert forum.stackstorm.com to GH static pages
- Source code of the "Daily forum posts integration" can be found here:  https://github.com/StackStorm/stackstorm-st2community/tree/master

**Comment by winem** [comment]
Those categories and tags/labels were migrated that seem to be useful right now. List of categories and labels may grow in the future but we decided to start with a short and clear one and extend it if needed.

**Comment by winem** [comment]
I'm currently testing the process and downloading the forum with wget and will  try to create GitHub pages on a private repo first. I'll have limited internet access until friday evening, so I'm not sure how far I'll get but I'll keep you posted.

**Comment by arm4b** [comment]
Let's use https://github.com/StackStorm/forum.stackstorm.com as a repository.
Feel free to push to the `main` branch to experiment with it.
Static HTML version for this repo is available at https://stackstorm.github.io/forum.stackstorm.com/

**Comment by arm4b** [comment]
The static HTML archive of the forum we wanted to keep for SEO was created and is now available at https://github.com/StackStorm/forum.stackstorm.com

**Comment by arm4b** [comment]
Switched `CNAME` to GH static pages.
forum.stackstorm.com is now officially based on static HTML archive and Discourse subscription is canceled.
