### ISSUE TITLE
TSC Meeting (05 Oct 2021): v3.6.0 Release Prep, Maintenance & Expenses

### ISSUE THREAD

**Issue by arm4b** [StackStorm/discussions#90]
October 2021 @StackStorm/tsc `1 hour` planned meeting: Tuesday, `05 Oct 2021, 09:30 AM US Pacific`.
See #33 for more info about how to join.

## Meeting Agenda

- StackStorm `v3.6.0` Preparation
  - Release Manager: @winem, Release Assistant: @guzzijones (per [release rotation](https://github.com/StackStorm/discussions/wiki/Release-Management-Rotation)).
  - [Roadmap](https://github.com/orgs/StackStorm/projects/22) - what do we keep for `v3.6.0`, what's moved to `v3.7.0`
  - TSC to process the PR backlog: https://github.com/StackStorm/st2/pulls?q=is%3Aopen+is%3Apr+milestone%3A3.6.0 - need at least `3-5` reviews from every @StackStorm/tsc member
  - Security updates
  - RabbitMQ repo update:
    - st2docs
    - bash installer
    - ansible
    - puppet
  - Define the approximate release start date & st2 master freeze
- [StackStorm Infra & Expenses](https://github.com/StackStorm/discussions/issues/36)
  - PackageCloud
    - PackageCloud partnership progress (`-$100/mo`) (#74). Packagecloud blog post - draft done, waiting for PackageCloud.
    - PackageCloud deb/rpm cleanup strategy
  - CloudSmith partnership
    - RabbitMQ uses both PackageCloud & [CloudSmith](https://www.rabbitmq.com/install-rpm.html#cloudsmith). We can start our research too. Anyone from @StackStorm/tsc to start the research?
  - Remove the @stackstorm.com G Suite personal email accounts in favor of a single shared email for all st2 operations (`-$50/mo`) - @armab
  - stackstorm.com website migration to static pages (`-$35/mo`) #76 - @nzlosh
  - Forum -> Github Discussions migration (`-$50/mo`) #89 - @cognifloyd @winem 
    - make forum read-only - done
    - create [GH Discussions](https://github.com/StackStorm/st2/discussions) - done
    - convert forum to GH static pages to avoid losing SEO/traffic
    - migrate Slack integrations
    - announce the migration/new platform: a blog post 
- Multi-lingual communities (example: #community-japan)
- Any other random Questions and Discussions

**Comment by cognifloyd** [comment]
I would also like to discuss action `output_schema` because I think we need some breaking changes to clean up the feature.
