### ISSUE TITLE
Upgrade RabbitMQ

### ISSUE THREAD

**Issue by amanda11** [StackStorm/discussions#91]
On EL8 distributions we use the latest RabbitMQ and Erlang from the rabbitMQ repos, but for all other distributions we use what is bundled with the O/S. Update all installations to use latest RabbitMQ.

Changes required for 3.6 release:
- [x] st2-packages - bash installer
- [x] st2docs
  - [x] installation and upgrade changes 
- [x] st2ci/cd - don't think necessary as in docs said was optional

  
 Changes that can be done post 3.6 release:
- [x] ansible installer - in progress @amanda11
- [x] puppet installer https://github.com/StackStorm/puppet-st2/

**Comment by arm4b** [comment]
@rush-skills Just created an issue for puppet-st2, https://github.com/StackStorm/puppet-st2/issues/340 if you'd like to take a look at updating RabbitMQ for https://github.com/StackStorm/puppet-st2/.

**Comment by rush-skills** [comment]
@armab You can close this one now, the changes are merged

**Comment by arm4b** [comment]
Thanks everyone :+1: 

The inconsistent RabbitMQ version shipped by default with the various distros was a bit of a security issue reported before by our users and so this definitely makes the project more secure.
