### ISSUE TITLE
Locked out of slack

### ISSUE THREAD

**Issue by punkrokk** [StackStorm/discussions#93]
I am locked out of slack. I did not get a notice of the exact date gmail accounts would be disabled, and I disagreed and offered to pay for mine. Please re-enable my account so I can get my slack profile back.

**Comment by arm4b** [comment]
The email address is valid as before, it's just configured to be a forwarder which you confirmed worked yesterday by [replying](https://user-images.githubusercontent.com/1533818/139557861-ff1104c7-43fc-4d74-b0df-3b7801d3ed06.png) to a message that was sent to your stackstorm email.
You can reset the password in Slack and get a reset link to the original email.
As for timing, we had almost 2 months wind-down period for this with the notification of everyone personally (by name) [in Slack](https://stackstorm-community.slack.com/archives/C020U70RZRR/p1631217827084500) and [TSC meeting](https://github.com/StackStorm/discussions/issues/87) plan.

**Comment by arm4b** [comment]
**UPDATE**: Looks like you figured it out, seeing your later message in Slack.
