### ISSUE TITLE
TSC Meeting (01 Mar 2022): AWS follow-up, v3.7.0 preparation

### ISSUE THREAD

**Issue by arm4b** [StackStorm/discussions#98]
March 2022 @StackStorm/tsc `1 hour` planned meeting: Tuesday, `01 Mar 2022, 09:30 AM US Pacific`.

See #33 for more info about how to join.
(TLDR; Zoom link: https://us02web.zoom.us/j/81082101702?pwd=N1V4TWdYRVQ4SXBsaFh1TFYvVDA0UT09)

### StackStorm AWS account follow-up ~(20min)
  - See previous meeting for the issue description and more context: https://github.com/StackStorm/community/issues/97
  - Update: Per [Slack](https://stackstorm-community.slack.com/archives/C020U70RZRR/p1645044415877409?thread_ts=1643826199.887169&cid=C020U70RZRR) and @punkrokk the AWS FOSS credits expiration date is `31-July-22`, not `31-March-22` as thought before
  - Discuss the AWS account/ownership migration
  - Discuss the ST2 infra future in the AWS

### StackStorm `v3.7.0` release preparation ~(40min)
  - Release Manager: @cognifloyd 
  - Release Assistant: still missing a volunteer. Who from @StackStorm/maintainers?
  - Target month: March 2022
  - Project & Roadmap: https://github.com/orgs/StackStorm/projects/23

**Comment by arm4b** [comment]
Some follow-up and stats from the AWS discussion today.

AWS Reducing costs project: https://github.com/orgs/StackStorm/projects/27

AWS monthly running costs for the latest `3mo`: `Dec '21`, `Jan '22`, `Feb '22`: 
![image](https://user-images.githubusercontent.com/1533818/156238654-ed88ab82-640b-4d8f-9d98-b50a44148cda.png)

AWS daily costs for the `Februrary '22` (avg ~`$21/day`):
![image](https://user-images.githubusercontent.com/1533818/156239441-f1f56754-e865-40e4-a166-2f96ece66e1c.png)


cc @bishopbm1

**Comment by nzlosh** [comment]
## Meeting minutes for TSC Meeting (01 Mar 2022): AWS follow-up, v3.7.0 preparation
### Attendees:

- Bradley Bishop
- Ankur Signh
- Eugen Cusmaunsa
- Jacob Floyd
- Amanda (amanda11)
- Carlos (nzlosh)
- AJ (guzzijones)
- Saurav Kumar

### AWS account ownership

Bradley Bishop of Encore Technology has talked internal about taking ownership of the StackStorm AWS Account (child) under the Encore Technology (parent) account.

A condition to Encore Technology taking on the StackStorm AWS account, they want to see a project plan outlining the actions the StackStorm project will take to reduce AWS operational costs.

### AWS Actions 

The TSC has agreed to create a Gtihub project board and fill in tasks that lead to the reduction of these costs.

Bradley is in contact with JP and will determine what day to day effort is required to manage an AWS parent account.

AJ (guzzijones) has been approved to work on StackStorm related work by his company and has offered to work on migrating  [API](https://github.com/StackStorm/st2apidocs/issues/16) and [documentation](https://github.com/StackStorm/st2docs/issues/1096) websites from AWS S3 to github pages.

Bradley offered his help with LDAP hosting in AWS if needed.  Eugen suggested LDAP could be replaced with another authentication solution to help reduce AWS costs.

 Bradley needs to determine how child/parent ownership works and long with other AWS details.  He'd like to target mid to late June to carry out the AWS migration.


### v3.7 Release Actions

Carlos (nzlosh) will be release assistant for v3.7

Carlos (nzlosh) will follow-up on issues #5152 #5143 and #4924 which are blocked in _in progress_.
